context:
  link: '#'
  heading: Page Title

  # Header
  dropdowns:
    - label: Books
      dropdownItems:
        - label: Bestsellers
        - label: New releases
        - label: Coming soon
        - label: E-books
        - label: All categories
    - label: Events
      dropdownItems:
        - label: Book signings
        - label: Press releases
        - label: Summer reading
    - label: Services
      dropdownItems:
        - label: Contact

  # Breadcrumbs
  pages:
    - title: Page
    - title: Page
    - title: Current page

  paragraphFirst: This site is solely for training and demonstration purposes. Any content used or marks identified have no relationship with products or services offered by the respective owners of such intellectual property.
  paragraphSecond: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.
  paragraphThird:  Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc
        
  # Footer
  footerTitle: About Us
  footerText: Rogers Bookstore.com leverages the power of the Ask Roger! brand to offer online customers the Web's premier destination for books, eBooks, magazines, toys & games, music, DVD and Blu-ray, and related products and services.
  copyrightText: Copyright © 2016 Version 1.0.0.0
  footerLinks:
    - label: Legal Notice
    - label: Privacy Policy
    - label: Terms and Conditions
    