context:
  link: '#'
  heading: Page Title
  sectionTitle: Section Title
  title: Shadow and Bone
  cardImg: '/pictures/img-1.png'
  linkText: 'Read more'

  # Header
  dropdowns:
    - label: Books
      dropdownItems:
        - label: Bestsellers
        - label: New releases
        - label: Coming soon
        - label: E-books
        - label: All categories
    - label: Events
      dropdownItems:
        - label: Book signings
        - label: Press releases
        - label: Summer reading
    - label: Services
      dropdownItems:
        - label: Contact

  pages:
    - title: Page
    - title: Page
    - title: Current page
  
  # Highlight card
  highlightTitle: Revival Season
  highlightButtonText: Buy this book
  paragraphs:
    - text: 'Every summer, fifteen-year-old Miriam Horton and her family pack themselves tight in their old minivan and travel through small southern towns for revival season: the time when Miriam’s father holds massive healing services for people desperate to be cured of ailments and disease. After one such service in which Reverend Horton’s healing powers are tested like never before, Miriam witnesses a shocking act of violence that shakes her belief in everything she’s known to be true.'
    - text: 'When the Hortons return home, Miriam’s confusion only grows as she discovers she might have the power to heal—even though her father and the church have always made it clear that such power is denied to women. Over the course of the next year, Miriam must decide between her religion, her family, and her newfound power that might be able to save others, but, if discovered by her father, could destroy Miriam.'

  # Card normal
  cardText: Leigh Bardugo is a master of YA Fantasy, and this is no exception to her talents.

  # Card wide
  cardWideText: Robert Fabbri was born in Geneva in 1961. He was educated at Christ’s Hospital School, Horsham and London University. He worked for twenty-five years as an assistant director in the film and television industries. Having had his fair share of long, cold nights standing in the rain in muddy fields and unbearably hot days in deserts or stuffy sound stages he decided to start writing. Being a life-long ancient war-gamer with a collection of over 3,500 hand-painted 25mm lead soldiers and a lover of Roman Historical Fiction the subject matter was obvious.

  # Footer
  footerTitle: About Us
  footerText: Rogers Bookstore.com leverages the power of the Ask Roger! brand to offer online customers the Web's premier destination for books, eBooks, magazines, toys & games, music, DVD and Blu-ray, and related products and services.
  copyrightText: Copyright © 2016 Version 1.0.0.0
  footerLinks:
    - label: Legal Notice
    - label: Privacy Policy
    - label: Terms and Conditions
    