context:
  cardImg: /pictures/img-1.png
variants:
  - name: default
    context: 
      title: Shadow and Bone
      cardText: Leigh Bardugo is a master of YA Fantasy, and this is no exception to her talents.
      linkText: Read more
  - name: card-wide
    context:
      cardWideText: Robert Fabbri was born in Geneva in 1961. He was educated at Christ’s Hospital School, Horsham and London University. He worked for twenty-five years as an assistant director in the film and television industries. Having had his fair share of long, cold nights standing in the rain in muddy fields and unbearably hot days in deserts or stuffy sound stages he decided to start writing. Being a life-long ancient war-gamer with a collection of over 3,500 hand-painted 25mm lead soldiers and a lover of Roman Historical Fiction the subject matter was obvious.
      linkText: Read more
  - name: event-cell
    context:
      eventCellTitle: Think Africa Book Club
      eventCellText: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mattis quis justo in dictum. Etiam consequat lectus in placerat efficitur. Curabitur nec gravida turpis, quis porta tortor. Aenean placerat cursus nisl. Proin sed mollis diam, eu eleifend justo. Mauris ullamcorper condimentum elit et ultrices. In hac habitasse platea dictumst. Mauris neque odio, finibus quis urna eu, commodo gravida lorem. Phasellus consectetur ligula at consequat ultricies.
      eventCellDate: May 18, 2021

      